# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-26 21:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TrackSplitsApp', '0002_auto_20171226_2106'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='athlete_id',
            field=models.IntegerField(default=-1),
        ),
    ]
