# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-26 21:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TrackSplitsApp', '0003_activity_athlete_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='workout_type',
            field=models.IntegerField(default=-1),
        ),
    ]
